### ISSUE TITLE
カラム変更機能

### ISSUE THREAD

**Issue by pandeiro245** [mashupwork/kintone_sync#18]
# TODO
- [x] KintoneSync::Migrationの追加
- [x] KintoneSync::Migration.copy_column
- [x] KintoneSync::Migration.tranfer_data
- [x] KintoneSync::Migration.drop_column
- [x] KintoneSync::Migration.rename_column（copyしてコピー元を削除）
- [x] KintoneSync::Migration.change_column（copyしてコピー先にデータ移してからコピー元を削除）
- [x] ドロップダウン→ラジオボックス
- [x] ラジオボックス→ドロップダウン
- [ ] １行テキスト→複数行テキスト
- [ ] 複数行テキスト→１数行テキスト
